name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.18.0'

      - name: Deploy Backend via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: feelsoul
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          timeout: 90s                            # give network a bit more time
          command_timeout: 30m
          debug: true
          script: |
            cd /home/feelsoul/apk/ScanMeBackend
            git pull origin main || true
            npm install --production
            pm2 restart feelsoul || pm2 start server.js --name feelsoul