name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.18.0'

      - name: Deploy Backend via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: jatin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/jatin/apps/my-app/ScanMeBackend
            git pull origin main || true
            npm install --production
            pm2 restart my-app || pm2 start server.js --name my-app