# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Node.js CI/CD

# on:
#   push:
#     branches: [ "main" ]
#   # pull_request:
#   #   branches: [ "main" ]

# jobs:
#   build:

#     runs-on: self-hosted

#     strategy:
#       matrix:
#         node-version: [20.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#     - uses: actions/checkout@v4
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v4
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: pm2 restart feelsoul || pm2 start server.js --name feelsoul

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    # Set the working directory for all 'run' steps in this job
    defaults:
      run:
        working-directory: /home/feelsoul/apk/ScanMeBackend

    steps:
    - name: Pull latest changes from the main branch
      run: git pull origin main
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        # Point the cache to the correct lock file location
        cache-dependency-path: /home/feelsoul/apk/ScanMeBackend/package-lock.json

    - name: Install dependencies using clean install
      run: npm ci

    - name: Restart application with PM2
      run: pm2 restart feelsoul || pm2 start server.js --name feelsoul
