name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      working-directory: /home/feelsoul/apk/ScanMeBackend
      run: npm ci --production

    - name: Restart Backend with PM2
      working-directory: /home/feelsoul/apk/ScanMeBackend
      run: |
        pm2 stop feelsoul || true
        pm2 delete feelsoul || true
        pm2 start server.js --name feelsoul
        pm2 save
